
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class BilgiEkranı extends javax.swing.JFrame {

    /**
     * Creates new form BilgiEkranı
     */
    DefaultTableModel Tablo = new DefaultTableModel();
    public BilgiEkranı() {
        initComponents();
        m_txttable.setModel(Tablo);
        Tablo.setColumnIdentifiers(new String[] {"Ad","Soyad","Numara","Plaka","Saat"});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_txtbiptal = new javax.swing.JButton();
        m_txtbdevamet = new javax.swing.JButton();
        m_txtbgiriş = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        m_txttable = new javax.swing.JTable();
        m_txtplaka = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        m_txtnumara = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        m_txtsaat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        m_txtsoyad = new javax.swing.JTextField();
        m_txtad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        m_txtbiptal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        m_txtbiptal.setText("İptal");
        m_txtbiptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_txtbiptalActionPerformed(evt);
            }
        });
        getContentPane().add(m_txtbiptal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 72, -1));

        m_txtbdevamet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        m_txtbdevamet.setText("Devam et");
        m_txtbdevamet.setEnabled(false);
        m_txtbdevamet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_txtbdevametActionPerformed(evt);
            }
        });
        getContentPane().add(m_txtbdevamet, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        m_txtbgiriş.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        m_txtbgiriş.setText("Giriş");
        m_txtbgiriş.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_txtbgirişActionPerformed(evt);
            }
        });
        getContentPane().add(m_txtbgiriş, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 75, -1));

        m_txttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(m_txttable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 373, 230));
        getContentPane().add(m_txtplaka, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 90, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Giriş saati:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        getContentPane().add(m_txtnumara, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 90, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Plaka:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("İletişim numarası:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        getContentPane().add(m_txtsaat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 90, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Soyadı:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Kullanıcı adı:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));
        getContentPane().add(m_txtsoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 90, -1));
        getContentPane().add(m_txtad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 90, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/f2.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_txtbgirişActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_txtbgirişActionPerformed
        String ad = m_txtad.getText();
        String soyad = m_txtsoyad.getText();
        String numara = m_txtnumara.getText();
        String plaka = m_txtplaka.getText();
        String giriş = m_txtsaat.getText();

        try{
            if(m_txtad.getText().equals("") || m_txtsoyad.getText().equals("") ||
                m_txtnumara.getText().equals("") || m_txtplaka.getText().equals("") ||
                m_txtsaat.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Boş yerleri lütfen doldurunuz!", "Uyari", JOptionPane.WARNING_MESSAGE);

            }
            else
            {
                String save_message= "Kayıt tamamlandı";
                JOptionPane.showMessageDialog(rootPane, save_message);
                Tablo.addRow(new String[] {ad,soyad,numara,plaka,giriş});
                m_txtbdevamet.setEnabled(true);
            }
        }
        catch(HeadlessException e){
            //   String save_message= "Kayıt tamamlanmıştır";
            JOptionPane.showMessageDialog(rootPane, "Hata");
        }

        //Tablo.addRow(new String[] {ad,soyad,numara,plaka,giriş});
    }//GEN-LAST:event_m_txtbgirişActionPerformed

    private void m_txtbdevametActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_txtbdevametActionPerformed
        ÜcretHesaplama hesapla = new ÜcretHesaplama();
        hesapla.setVisible(true);
        dispose();
    }//GEN-LAST:event_m_txtbdevametActionPerformed

    private void m_txtbiptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_txtbiptalActionPerformed
        m_txtad.setText("");
        m_txtsoyad.setText("");
        m_txtnumara.setText("");
        m_txtplaka.setText("");
        m_txtsaat.setText("");
    }//GEN-LAST:event_m_txtbiptalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BilgiEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BilgiEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BilgiEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BilgiEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BilgiEkranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField m_txtad;
    private javax.swing.JButton m_txtbdevamet;
    private javax.swing.JButton m_txtbgiriş;
    private javax.swing.JButton m_txtbiptal;
    private javax.swing.JTextField m_txtnumara;
    private javax.swing.JTextField m_txtplaka;
    private javax.swing.JTextField m_txtsaat;
    private javax.swing.JTextField m_txtsoyad;
    private javax.swing.JTable m_txttable;
    // End of variables declaration//GEN-END:variables
}
