
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class Kart extends javax.swing.JFrame {

    String no;
    /**
     * Creates new form Kart
     */
    public Kart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        m_taksit = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        m_onayla = new javax.swing.JButton();
        m_kartnumarası = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 150));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Kart numarası:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 42, -1, -1));

        m_taksit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tek çekim", "2 taksit", "3 taksit", "6 taksit" }));
        m_taksit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_taksitActionPerformed(evt);
            }
        });
        getContentPane().add(m_taksit, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 92, -1, -1));

        jLabel2.setText("Taksit seçeneği:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 95, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 178, -1, -1));

        jLabel4.setText("Ödemeyi onaylayınız");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 155, -1, -1));

        m_onayla.setText("Onayla");
        m_onayla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_onaylaActionPerformed(evt);
            }
        });
        getContentPane().add(m_onayla, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 185, 81, -1));

        m_kartnumarası.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_kartnumarasıActionPerformed(evt);
            }
        });
        getContentPane().add(m_kartnumarası, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 39, 81, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/f4.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_taksitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_taksitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_taksitActionPerformed

    private void m_kartnumarasıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_kartnumarasıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_kartnumarasıActionPerformed

    private void m_onaylaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_onaylaActionPerformed
        // TODO add your handling code here:
            
            
      try{
         if (m_kartnumarası.getText().length()>11||m_kartnumarası.getText().length()<11){
            throw new Exception();
            
         }
         else{
             no = m_kartnumarası.getText();
              JOptionPane.showMessageDialog(null,"Ödeme tamamlandı");
              // JOptionPane.showMessageDialog(null,"Kart numarası hatalı tekrar deneyiniz");  
             dispose();
              }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Kart numarası hatalı tekrar deneyiniz");       
        }
       
    
      // dispose();
        
    }//GEN-LAST:event_m_onaylaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField m_kartnumarası;
    private javax.swing.JButton m_onayla;
    private javax.swing.JComboBox<String> m_taksit;
    // End of variables declaration//GEN-END:variables
}
