
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class Ödeme extends javax.swing.JFrame {

    /**
     * Creates new form Ödeme
     */
    public Ödeme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_nasıl = new javax.swing.JLabel();
        m_nakit = new javax.swing.JButton();
        m_kart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        m_nasıl.setText("Ödemeyi nasıl yapmak istediğinizi seçiniz:");
        getContentPane().add(m_nasıl, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 42, 287, 36));

        m_nakit.setText("Nakit");
        m_nakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_nakitActionPerformed(evt);
            }
        });
        getContentPane().add(m_nakit, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 91, 77, -1));

        m_kart.setText("Kredi Kartı");
        m_kart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_kartActionPerformed(evt);
            }
        });
        getContentPane().add(m_kart, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 91, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/f4.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_nakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_nakitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Lütfen kasaya gidiniz");
        dispose();
    }//GEN-LAST:event_m_nakitActionPerformed

    private void m_kartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_kartActionPerformed
        // TODO add your handling code here:
           Kart kart = new Kart();
           kart.setVisible(true);
           dispose();
    }//GEN-LAST:event_m_kartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ödeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ödeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ödeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ödeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ödeme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton m_kart;
    private javax.swing.JButton m_nakit;
    private javax.swing.JLabel m_nasıl;
    // End of variables declaration//GEN-END:variables
}
