
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class ÜcretHesaplama extends javax.swing.JFrame {

    /**
     * Creates new form ÜcretHesaplama
     */
    public ÜcretHesaplama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        m_txtcombobox = new javax.swing.JComboBox<>();
        m_txtbgönder = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Otoparkta kaç saat kalacağınızı seçiniz:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 89, -1, -1));

        m_txtcombobox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        m_txtcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "1", "2", "3", "4", "5", "6", "6+" }));
        m_txtcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_txtcomboboxActionPerformed(evt);
            }
        });
        getContentPane().add(m_txtcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 86, -1, -1));

        m_txtbgönder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        m_txtbgönder.setText("Gönder");
        m_txtbgönder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_txtbgönderActionPerformed(evt);
            }
        });
        getContentPane().add(m_txtbgönder, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 139, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/q2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_txtcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_txtcomboboxActionPerformed
      
    }//GEN-LAST:event_m_txtcomboboxActionPerformed

    private void m_txtbgönderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_txtbgönderActionPerformed
           if(m_txtcombobox.getSelectedItem().equals("1")){
           JOptionPane.showMessageDialog(null,"Ücretiniz 7 TL'dir.");
           }
           else if(m_txtcombobox.getSelectedItem().equals("2")){
           JOptionPane.showMessageDialog(null,"Ücretiniz 9 TL'dir.");
           }
           else if(m_txtcombobox.getSelectedItem().equals("3")){
           JOptionPane.showMessageDialog(null,"Ücretiniz 11 TL'dir.");
           }
           else if(m_txtcombobox.getSelectedItem().equals("4")){
           JOptionPane.showMessageDialog(null,"Ücretiniz 13 TL'dir.");
           }
           else if(m_txtcombobox.getSelectedItem().equals("5")){
           JOptionPane.showMessageDialog(null,"Ücretiniz 15 TL'dir.");
           }
           else if(m_txtcombobox.getSelectedItem().equals("6")){
           JOptionPane.showMessageDialog(null,"Ücretiniz 17 TL'dir.");
           }
           else if(m_txtcombobox.getSelectedItem().equals("6+")){
           JOptionPane.showMessageDialog(null,"Ücretiniz 20 TL'dir.");
           }
           
           Karar karar = new Karar();
           karar.setVisible(true);
           dispose();
           
           
    }//GEN-LAST:event_m_txtbgönderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ÜcretHesaplama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ÜcretHesaplama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ÜcretHesaplama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ÜcretHesaplama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ÜcretHesaplama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton m_txtbgönder;
    private javax.swing.JComboBox<String> m_txtcombobox;
    // End of variables declaration//GEN-END:variables
}
